# Docker Compose file for MicroBin
services:
  microbin:
    container_name: microbin
    hostname: microbin
    image: danielszabo99/microbin:latest
    restart: unless-stopped
    networks:
      - reverse-proxy-net
    ports:
     - "\${MICROBIN_PORT}:8080"
    volumes:
     - microbin-data:/app/microbin_data
    environment:
      MICROBIN_BASIC_AUTH_USERNAME: \${MICROBIN_BASIC_AUTH_USERNAME}
      MICROBIN_BASIC_AUTH_PASSWORD: \${MICROBIN_BASIC_AUTH_PASSWORD}
      MICROBIN_ADMIN_USERNAME: \${MICROBIN_ADMIN_USERNAME}
      MICROBIN_ADMIN_PASSWORD: \${MICROBIN_ADMIN_PASSWORD}
      MICROBIN_EDITABLE: \${MICROBIN_EDITABLE}
      MICROBIN_FOOTER_TEXT: \${MICROBIN_FOOTER_TEXT}
      MICROBIN_HIDE_FOOTER: \${MICROBIN_HIDE_FOOTER}
      MICROBIN_HIDE_HEADER: \${MICROBIN_HIDE_HEADER}
      MICROBIN_HIDE_LOGO: \${MICROBIN_HIDE_LOGO}
      MICROBIN_NO_LISTING: \${MICROBIN_NO_LISTING}
      MICROBIN_HIGHLIGHTSYNTAX: \${MICROBIN_HIGHLIGHTSYNTAX}
      MICROBIN_BIND: \${MICROBIN_BIND}
      MICROBIN_PRIVATE: \${MICROBIN_PRIVATE}
      MICROBIN_PURE_HTML: \${MICROBIN_PURE_HTML}
      MICROBIN_DATA_DIR: \${MICROBIN_DATA_DIR}
      MICROBIN_JSON_DB: \${MICROBIN_JSON_DB}
      MICROBIN_PUBLIC_PATH: \${MICROBIN_PUBLIC_PATH}
      MICROBIN_SHORT_PATH: \${MICROBIN_SHORT_PATH}
      MICROBIN_READONLY: \${MICROBIN_READONLY}
      MICROBIN_UPLOADER_PASSWORD: \${MICROBIN_UPLOADER_PASSWORD}
      MICROBIN_SHOW_READ_STATS: \${MICROBIN_SHOW_READ_STATS}
      MICROBIN_TITLE: \${MICROBIN_TITLE}
      MICROBIN_THREADS: \${MICROBIN_THREADS}
      MICROBIN_GC_DAYS: \${MICROBIN_GC_DAYS}
      MICROBIN_ENABLE_BURN_AFTER: \${MICROBIN_ENABLE_BURN_AFTER}
      MICROBIN_DEFAULT_BURN_AFTER: \${MICROBIN_DEFAULT_BURN_AFTER}
      MICROBIN_WIDE: \${MICROBIN_WIDE}
      MICROBIN_QR: \${MICROBIN_QR}
      MICROBIN_ETERNAL_PASTA: \${MICROBIN_ETERNAL_PASTA}
      MICROBIN_ENABLE_READONLY: \${MICROBIN_ENABLE_READONLY}
      MICROBIN_DEFAULT_EXPIRY: \${MICROBIN_DEFAULT_EXPIRY}
      MICROBIN_NO_FILE_UPLOAD: \${MICROBIN_NO_FILE_UPLOAD}
      MICROBIN_CUSTOM_CSS: \${MICROBIN_CUSTOM_CSS}
      MICROBIN_HASH_IDS: \${MICROBIN_HASH_IDS}
      MICROBIN_ENCRYPTION_CLIENT_SIDE: \${MICROBIN_ENCRYPTION_CLIENT_SIDE}
      MICROBIN_ENCRYPTION_SERVER_SIDE: \${MICROBIN_ENCRYPTION_SERVER_SIDE}
      MICROBIN_MAX_FILE_SIZE_ENCRYPTED_MB: \${MICROBIN_MAX_FILE_SIZE_ENCRYPTED_MB}
      MICROBIN_MAX_FILE_SIZE_UNENCRYPTED_MB: \${MICROBIN_MAX_FILE_SIZE_UNENCRYPTED_MB}
      TZ: Africa/Johannesburg
    labels:
      com.centurylinklabs.watchtower.enable: true
volumes:
  microbin-data:
    # Specify name so it does not append stack name
    name: microbin-data
networks:
  reverse-proxy-net:
    # Network is for reverse proxy to connect to container services
    external: true
    # Specify name so that it does not append stack name
    name: reverse-proxy-net
